#pragma once

#include <VoidEngine/Core/Common.hpp>

namespace VOID_NS {
    enum class Keycode : i32 {
        Unknown = -1,
    
        Space,
        Apostrophe,
        ExclamationMark,
        DoubleQuote,
        Hashtag,
        Dollar,
        Percent,
        Ampersand,
        SingleQuote,
        LeftParenthesis,
        ReftParenthesis,
        Asterisk,
        Plus,
        Comma,
        Minus,
        Period,
        Slash,
        Zero,
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,
        Colon,
        Semicolon,
        LessThan,
        Equal,
        GreaterThan,
        QuestionMark,
        AtSign,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        LeftSquareBracket,
        Backslash,
        RightSquareBracket,
        Caret,
        Underscore,
        Grave,
        LeftCurlyBracket,
        VerticalBar,
        RightCurlyBracket,
        Tilde,
    
        Count
    };
};
