#ifndef VOID_INPUT_KEYCODES_H__
#define VOID_INPUT_KEYCODES_H__

#include <VoidEngine/Core/Common.hpp>

namespace VOID_NS {
    typedef enum {
        Unknown = -1,
    
        KeySpace,
        KeyApostrophe,
        KeyExclamationMark,
        KeyDoubleQuote,
        KeyHashtag,
        KeyDollar,
        KeyPercent,
        KeyAmpersand,
        KeySingleQuote,
        KeyLeftParenthesis,
        KeyReftParenthesis,
        KeyAsterisk,
        KeyPlus,
        KeyComma,
        KeyMinus,
        KeyPeriod,
        KeySlash,
        KeyZero,
        KeyOne,
        KeyTwo,
        KeyThree,
        KeyFour,
        KeyFive,
        KeySix,
        KeySeven,
        KeyEight,
        KeyNine,
        KeyColon,
        KeySemicolon,
        KeyLessThan,
        KeyEqual,
        KeyGreaterThan,
        KeyQuestionMark,
        KeyAtSign,
        KeyA,
        KeyB,
        KeyC,
        KeyD,
        KeyE,
        KeyF,
        KeyG,
        KeyH,
        KeyI,
        KeyJ,
        KeyK,
        KeyL,
        KeyM,
        KeyN,
        KeyO,
        KeyP,
        KeyQ,
        KeyR,
        KeyS,
        KeyT,
        KeyU,
        KeyV,
        KeyW,
        KeyX,
        KeyY,
        KeyZ,
        KeyLeftSquareBracket,
        KeyBackslash,
        KeyRightSquareBracket,
        KeyCaret,
        KeyUnderscore,
        KeyGrave,
        KeyLeftCurlyBracket,
        KeyVerticalBar,
        KeyRightCurlyBracket,
        KeyTilde,
    
        MAX_KEYCODES
    } Keycode;
};

#endif /* VOID_INPUT_KEYCODES_H__ */
